tab_emojis: "ğŸ¶ğŸ±ğŸ­ğŸ¦ŠğŸ»ğŸ¼ğŸ®ğŸ·ğŸ¸ğŸµğŸ¦‰ğŸ¦„ğŸŸğŸ³ğŸ–ğŸ‚ğŸ’¥ğŸŒˆğŸŒ"
mode: "vim" #`vim` or `easy`

group:
  -
    name: "tools"
    item:
      - { title: "hello", exec: "echo hello devgo" }
      - { title: "date now", exec: "date" }
  -
    name: "website"
    item:
      - { title: "github", exec: "open https://github.com" }

  -
    name: "devgo"
    item:
      - { title: "edit config", exec: "vim $HOME/.devgo.yaml" }
