# random group tab name preifx emoji
tab_emojis="ğŸ¶ğŸ±ğŸ­ğŸ¦ŠğŸ»ğŸ¼ğŸ®ğŸ·ğŸ¸ğŸµğŸ¦‰ğŸ¦„ğŸŸğŸ³ğŸ–ğŸ‚ğŸ’¥ğŸŒˆğŸŒ"
mode="easy"

[[group]]
# group name
name="tools"
[[group.item]]
# group item title
title="hello"
# group item command to exec
exec="echo hello devgo"
[[group.item]]
title="date now"
exec="date"

[[group]]
name="website"
[[group.item]]
title="github"
exec="open https://github.com"

[[group]]
name="devgo"
[[group.item]]
title="edit config"
exec="vim $HOME/.devgo.toml"
